[build]
  functions = "netlify/functions" # Ensure this points to your functions directory
  publish = "/"
  command = ""

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
