[build]
  functions = "netlify/functions"
  publish = "."  # Adjust this if you're using a build process (e.g., Webpack, React, etc.)

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
